version: '2'

services:
  backend:
    build: .
    ports:
      - 8000:8000
      - 9229:9229 #debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:docker #this will replace the start command in the dockerfile
    environment:
      PORT: 8000
